### ISSUE TITLE
Fill out missing functions

### ISSUE THREAD

**Issue by thatch45** [saltstack/libnacl#1]
We want to get all functions in libsodium wrapped

**Comment by lvzon** [comment]
Because I needed to interface to a C-based project that used crypto_box_easy and some other functions, I copied your bindings and added a number of functions. It should be easy to create a diff from the following commit: https://github.com/lvzon/libsodium-python/commit/a4b0e22ad5118ea2f9ceb24e47a321d46ffd1195

**Comment by thatch45** [comment]
@lvzon I would love to get these functions into libnacl rather then introduce more schisms in the available libsodium python bindings.
I will look into getting these into libnacl, but if you could make a PR I would be more than happy to merge it in. That would speed things up just because it might be a few days before I can get these into libnacl and cut a release.

**Comment by lvzon** [comment]
@thatch45 I made a pull request with the functions I added: https://github.com/saltstack/libnacl/pull/102

**Comment by thatch45** [comment]
Old issue, we have added a bunch!
