### ISSUE TITLE
Missing 0.18.0 tag/commits

### ISSUE THREAD

**Issue by mgorny** [saltstack/libnacl#131]
It seems that 1.8.0 was added to pypi without pushing the relevant commits/tag here.

**Comment by fabaff** [comment]
This is a blocker for all the distributions which are using the GitHub releases to build packages.

**Comment by mgorny** [comment]
Ping.

**Comment by mgorny** [comment]
It seems that also the commit updating `libnacl/version.py` is missing. Either way, I've forked the repository and pushed the tag (along with version update) to my fork.

**Comment by thatch45** [comment]
Sorry I have been so slow on this, I need to get someone assigned to libnacl, I just don't have the time to keep up on this. Let me circle back about bringing in more people for maintinance.

**Comment by thatch45** [comment]
ok, we will be meeting on how to get this resolved in the next few days so that we can get over these lapses

**Comment by thesamesam** [comment]
Any news?

**Comment by thatch45** [comment]
I just pushed the tag for 1.8.0 and 1.9.0

**Comment by mgorny** [comment]
Thank you, for this and the other fix!

**Comment by thatch45** [comment]
Thanks for sticking around, I have not been able to be as active on Github for a while, hopefully I can be more active here. I have missed this project!
Every now and then I look at pynacl, they have done an amazing job, but I just prefer how libnacl is laid out, and it has features that are important to me. Which makes sense - since I wrote it :)
